# Generated by Django 3.1.6 on 2021-02-08 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0004_list_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_to_add',
            field=models.CharField(blank=True, max_length=75),
        ),
    ]
