# Generated by Django 3.1.6 on 2021-02-08 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0005_item_item_to_add'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='List',
            new_name='ToDoList',
        ),
    ]
