# Generated by Django 3.1.6 on 2021-02-09 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0007_delete_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('completed', models.BooleanField(default=False)),
                ('to_do_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lists.todolist')),
            ],
        ),
    ]
