# Generated by Django 3.1.6 on 2021-02-09 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0010_auto_20210209_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='to_do_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='lists.todolist'),
        ),
    ]
